# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kylie Stradley
tagline:          ''
description:      'Web Developer'
url:              kyfast.net

author:
  name:           'Kylie Stradley'
  url:            https://twitter.com/kyfast

paginate:         5

# # Custom vars
# version:          2.0.0

github:             https://github.com/kyfast
#   repo:           https://github.com/poole/hyde