# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            kylie stradley
tagline:          ''
description:      'web developer'
url:              kyfast.net

author:
  name:           'Kylie Stradley'
  url:
  github:         kyfast
  twitter:        kyfast
  email:          ky@kyfast.net

paginate:         5
related_posts_max: 3

# # Custom vars
# version:          2.0.0

github:             https://github.com/kyfast
#   repo:           https://github.com/poole/hyde
