# Dependencies
markdown:         redcarpet
highlighter:      true
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            kylie stradley
tagline:          'A Blog About a Developing Developer'
description:      'web developer'
url:              http://kyfast.net
name:             "Kylie's Blog"

author:
  name:           'Kylie Stradley'
  url:            kyfast.net
  github:         kyfast
  twitter:        kyfast
  email:          ky@kyfast.net

paginate:         5
related_posts_max: 3

# # Custom vars
# version:          2.0.0

github:             https://github.com/kyfast
#   repo:           https://github.com/poole/hyde
